### ISSUE TITLE
Is speaker travel (airfare + hotel) supported by you or not? 

### ISSUE THREAD

**Issue by siakaramalegos** [wikimedia/fosdem20-web-performance-cfp#1]
Just wanted to check before submitting, thanks.

**Comment by gi11es** [comment]
Hi Sia,

We can probably afford it for 1 or 2 speakers. Please submit your proposal and indicate alongside it where you need to fly from and how many hotel nights you need. It's perfectly fine for you talk to be dependent on our ability to sponsor your travel, and we will make sure that we will only announce your talk (if we select it, of course) if we have secured your travel budget.

**Comment by gi11es** [comment]
Deadline is today, I hope you will consider applying 🙃

**Comment by siakaramalegos** [comment]
@gi11es Thanks for the reminder. I'm submitting now. You are not interested in workshops, correct? Only "lectures"?

**Comment by gi11es** [comment]
As long as it fits in 35 minutes (questions included for a talk), hands-on workshops are fine too!
